// Polsk oversettelse av brukerflaten (generert fra norske tekster i koden).
// Nøkkel = norsk tekst slik den står på skjermen. Mangler en tekst, vises den norske.
export const PL_TEKST: Record<string, string> = {
"jan": "sty",
"feb": "lut",
"mar": "mar",
"apr": "kwi",
"mai": "maj",
"jun": "cze",
"jul": "lip",
"aug": "sie",
"sep": "wrz",
"okt": "paź",
"nov": "lis",
"des": "gru",
"internt": "wewnętrzne",
"interntid (": "czas wewnętrzny (",
"interntid": "czas wewnętrzny",
"Internt": "Wewnętrzne",
"timer": "godz.",
"t": "godz.",
"i dag": "dzisiaj",
"I dag": "Dzisiaj",
"Lagrer …": "Zapisywanie …",
"man": "pon",
"tir": "wt",
"ons": "śr",
"tor": "czw",
"fre": "pt",
"lør": "sob",
"søn": "nd",
"Man": "Pon",
"Tir": "Wt",
"Ons": "Śr",
"Tor": "Czw",
"Fre": "Pt",
"Lør": "Sob",
"Søn": "Nd",
"Starter …": "Uruchamianie …",
"Noe gikk galt": "Coś poszło nie tak",
"Prøv igjen": "Spróbuj ponownie",
"Henter ferieplanen …": "Pobieranie danych …",
"Du har ikke tilgang ennå": "Nie masz jeszcze dostępu",
"Du er logget inn som": "Jesteś zalogowany jako",
", men den adressen er ikke registrert som ansatt. Be leder legge den inn under Oppsett, og last siden på nytt.": ", ale ten adres nie jest zarejestrowany jako pracownik. Poproś kierownika o dodanie go w Ustawieniach i odśwież stronę.",
"Sjekk igjen": "Sprawdź ponownie",
"Logg ut": "Wyloguj",
"Timer": "Godziny",
"Prosjekter": "Projekty",
"Avvik": "Zdarzenia",
"Utstyr": "Sprzęt",
"Rapporter": "Raporty",
"Fravær": "Nieobecność",
"Lønn": "Wynagrodzenie",
"Oppsett": "Ustawienia",
"Ferie": "Urlop",
"Syk": "Choroba",
"Kalender": "Kalendarz",
"Søknader": "Wnioski",
"Regler": "Zasady",
"· leder": "· kierownik",
"Demo": "Demo",
"Eksempeldata som bare ligger i denne nettleseren. Koble til Supabase for ekte bruk.": "Przykładowe dane zapisane tylko w tej przeglądarce.",
"Ny rapport:": "Nowy raport:",
"Les nå": "Czytaj teraz",
"Ferieår": "Rok urlopowy",
"Logg inn": "Zaloguj",
"Demomodus. Velg hvem du vil logge inn som.": "Tryb demo. Wybierz, jako kto chcesz się zalogować.",
"Skriv inn jobb-e-posten din. Du får en kode på e-post.": "Wpisz swój służbowy e-mail. Otrzymasz kod e-mailem.",
"E-post": "E-mail",
"Sender …": "Wysyłanie …",
"Send kode": "Wyślij kod",
"Vi har sendt en kode til": "Wysłaliśmy kod na adres",
"Kode": "Kod",
"Logger inn …": "Logowanie …",
"Bruk en annen e-post": "Użyj innego adresu e-mail",
"Søndag": "Niedziela",
"Mandag": "Poniedziałek",
"Tirsdag": "Wtorek",
"Onsdag": "Środa",
"Torsdag": "Czwartek",
"Fredag": "Piątek",
"Lørdag": "Sobota",
"Internt arbeid": "Praca wewnętrzna",
"Ukjent prosjekt": "Nieznany projekt",
"Timene er endret": "Godziny zostały zmienione",
"Viser for": "Pokaż dla",
"Syk i dag? Meld egenmelding": "Chory dzisiaj? Zgłoś zwolnienie",
"Mangler timer": "Brakuje godzin",
"denne uka:": "w tym tygodniu:",
"Før for": "Wpisz dla",
"Glemt å logge inn?": "Zapomniałeś się zalogować?",
"Timer skal helst logges inn og ut i sanntid. Har du glemt det, kan du føre timene manuelt. De merkes da som «ført etterpå».": "Godziny najlepiej rejestrować na bieżąco (wejście i wyjście). Jeśli zapomniałeś, możesz wpisać je ręcznie. Zostaną oznaczone jako «wpisane później».",
"Før timer manuelt": "Wpisz godziny ręcznie",
"Endre timer": "Zmień godziny",
"Før timer": "Wpisz godziny",
"Dato": "Data",
"Fra": "Od",
"Til": "Do",
"Prosjekt": "Projekt",
"Internt arbeid (butikk, lager, verksted)": "Praca wewnętrzna (sklep, magazyn, warsztat)",
"Siste prosjekter": "Ostatnie projekty",
"Fakturerbart (faktureres kunden)": "Do fakturowania (fakturowane klientowi)",
"Hadde lunsj (": "Była przerwa obiadowa (",
"min trekkes)": "min odliczane)",
"Kjøring (km)": "Przejazd (km)",
"Reisetid (timer)": "Czas podróży (godz.)",
"Hva ble gjort": "Co zostało zrobione",
"F.eks. montert vinduer 2. etasje": "Np. zamontowane okna na 2. piętrze",
"Lagre endring": "Zapisz zmianę",
"Registrer": "Zarejestruj",
"Avbryt": "Anuluj",
"Lukk": "Zamknij",
"Sluttid må være etter starttid.": "Godzina zakończenia musi być po godzinie rozpoczęcia.",
"Uke": "Tydzień",
"Forrige uke": "Poprzedni tydzień",
"Neste uke": "Następny tydzień",
"Normaltid": "Czas normalny",
"Overtid 50 %": "Nadgodziny 50 %",
"Overtid 100 %": "Nadgodziny 100 %",
"Vis hele dagen": "Pokaż cały dzień",
"Lunsj er ikke registrert –": "Przerwa obiadowa nie jest zarejestrowana –",
"min trekkes.": "min zostanie odliczone.",
"· ikke fakturerbart": "· nie do fakturowania",
"Ført i etterkant, ikke logget inn/ut": "Wpisane później, bez logowania wejścia/wyjścia",
"Ført etterpå": "Wpisane później",
"Logget inn/ut, men tidene er rettet etterpå": "Zalogowane wejście/wyjście, ale godziny poprawiono później",
"Rettet": "Poprawione",
"Importert fra Svenn": "Zaimportowane ze Svenn",
"Fra Svenn": "Ze Svenn",
"Godkjent": "Zatwierdzone",
"Levert": "Złożone",
"Endre": "Zmień",
"Slettet": "Usunięto",
"Slett": "Usuń",
"Ingen timer.": "Brak godzin.",
"Godkjenn uke": "Zatwierdź tydzień",
"Åpnet for endring": "Otwarto do zmian",
"Åpne uka for endring": "Otwórz tydzień do zmian",
"God morgen": "Dzień dobry",
"Hei": "Cześć",
"God kveld": "Dobry wieczór",
"ingen økter ennå": "brak sesji",
"Logger du inn nå, står du inne fra": "Jeśli zalogujesz się teraz, będziesz na miejscu od",
"Logg inn nå ·": "Zaloguj teraz ·",
"Logget inn": "Zalogowany",
"kl.": "godz.",
"Også inne her:": "Też tutaj:",
"Du ble ikke logget ut": "Nie wylogowałeś się",
"Du har vært logget inn i over 10 timer. Glemt å logge ut?": "Jesteś zalogowany ponad 10 godzin. Zapomniałeś się wylogować?",
"Sluttet kl.": "Skończyłem o",
"– lunsj er alt ført i dag": "– przerwa obiadowa już wpisana dzisiaj",
"Logget ut – timene er lagret": "Wylogowano – godziny zapisane",
"Logg ut – dagen er ferdig": "Wyloguj – koniec dnia",
"Ferdig her – bytt til et annet prosjekt": "Skończone tutaj – przejdź do innego projektu",
"Bytt til": "Przełącz na",
"Inne nå": "Teraz na miejscu",
"Ingen er logget inn akkurat nå.": "Nikt nie jest teraz zalogowany.",
"· siden": "· od",
"– ikke logget ut!": "– nie wylogowany!",
"Ikke logget inn:": "Niezalogowani:",
"Dagen": "Dzień",
"Forrige dag": "Poprzedni dzień",
"Neste dag": "Następny dzień",
"hele laget": "cały zespół",
"Vis hele laget": "Pokaż cały zespół",
"Ingenting registrert denne dagen.": "Nic nie zarejestrowano tego dnia.",
"skrevet senere": "napisane później",
"Bilde": "Zdjęcie",
"Kundetimer og interntid": "Godziny dla klientów i czas wewnętrzny",
"Hvem": "Kto",
"Snekkere og allround": "Stolarze i pracownicy ogólni",
"Hittil i år": "Od początku roku",
"Fakturerbart": "Do fakturowania",
"Prosjekt, ikke fakt.": "Projekt, nie do fakt.",
"Interntid": "Czas wewnętrzny",
"Timer per måned fordelt på fakturerbart, ikke fakturerbart og interntid": "Godziny miesięcznie: do fakturowania, nie do fakturowania i wewnętrzne",
"t totalt –": "godz. łącznie –",
"fakturerbart,": "do fakturowania,",
"på prosjekt uten faktura,": "na projekcie bez faktury,",
"Interntid forrige måned:": "Czas wewnętrzny w poprzednim miesiącu:",
"Ikke fakt.": "Nie do fakt.",
"Andel intern": "Udział wewn.",
"Føringer som ikke ble logget inn/ut i sanntid": "Wpisy bez logowania na bieżąco",
"Trykk på en måned for detaljer. Interntid er timer uten prosjekt (butikk, lager, verksted).": "Kliknij miesiąc, aby zobaczyć szczegóły. Czas wewnętrzny to godziny bez projektu (sklep, magazyn, warsztat).",
"Bilder": "Zdjęcia",
"Bildet er": "Zdjęcie zostało",
"Laster opp …": "Przesyłanie …",
"Ta bilde": "Zrób zdjęcie",
"Fra galleri": "Z galerii",
"Bildet er slettet": "Zdjęcie usunięte",
"Avviket er meldt. Takk!": "Zgłoszenie wysłane. Dziękujemy!",
"Meld avvik": "Zgłoś zdarzenie",
"Alt som gikk galt eller kunne gått galt: feil i arbeid eller materiell, farlige forhold, nestenulykker og skader. Alle i bedriften ser meldingene.": "Wszystko, co poszło źle lub mogło pójść źle: błędy w pracy lub materiale, niebezpieczne sytuacje, zdarzenia potencjalnie wypadkowe i urazy. Wszyscy w firmie widzą zgłoszenia.",
"Type": "Typ",
"Ikke knyttet til prosjekt": "Niezwiązane z projektem",
"Hva skjedde?": "Co się stało?",
"Kort, f.eks. «Løst rekkverk i trapp»": "Krótko, np. «Luźna balustrada na schodach»",
"Beskrivelse": "Opis",
"Hvor, når, og hva som bør gjøres": "Gdzie, kiedy i co należy zrobić",
"Legg ved bilder": "Dodaj zdjęcia",
"Fjern": "Usuń",
"Avvik på prosjektet": "Zdarzenia na projekcie",
"Åpne": "Otwarte",
"Mine": "Moje",
"Alle": "Wszystkie",
"Ingen åpne avvik.": "Brak otwartych zdarzeń.",
"Ingen avvik.": "Brak zdarzeń.",
"Avviket er lukket": "Zdarzenie zamknięte",
"Lagret": "Zapisano",
"· meldt av": "· zgłosił(a)",
"(forsinket)": "(opóźnione)",
"Skjul": "Ukryj",
"Vis": "Pokaż",
"Tiltak:": "Działania:",
"Ansvarlig": "Odpowiedzialny",
"Ingen": "Brak",
"Frist": "Termin",
"Tiltak": "Działania",
"Hva er gjort for å rette opp og hindre at det skjer igjen": "Co zrobiono, aby to naprawić i zapobiec powtórzeniu",
"Status": "Status",
"Lagre": "Zapisz",
"Avviket er slettet": "Zdarzenie usunięte",
"Mitt utstyr": "Mój sprzęt",
"Kvoter for arbeidstøy og vernesko": "Limity odzieży roboczej i obuwia ochronnego",
"siste 12 mnd": "ostatnie 12 mies.",
"Nytt mot gammelt": "Nowy za stary",
"Ny": "Nowy",
"– har fra før": "– ma już",
"). Er den gamle levert inn?": "). Czy stary został zwrócony?",
"Den gamle er merket levert inn": "Stary oznaczony jako zwrócony",
"Ja, levert inn": "Tak, zwrócony",
"Merket: beholder begge": "Oznaczono: zatrzymuje oba",
"Beholder begge": "Zatrzymuję oba",
"Hentes fra utstyrskontoen i Visma:": "Pobierane z konta sprzętu w Visma:",
"har ingen utstyrskonto i Visma ennå": "nie ma jeszcze konta sprzętu w Visma",
"– velg den under Oppsett.": "– wybierz je w Ustawieniach.",
"Verneutstyr (hansker, briller, hørselvern o.l.) gis etter behov – vernesko har kvote.": "Środki ochrony (rękawice, okulary, ochronniki słuchu itp.) wydawane są według potrzeb – obuwie ochronne ma limit.",
"Kategori": "Kategoria",
"Alle (": "Wszystkie (",
"+ Registrer eget verktøy": "+ Zarejestruj własne narzędzie",
"Vis også levert inn og tapt": "Pokaż też zwrócone i zgubione",
"Ingenting registrert her.": "Nic tu nie zarejestrowano.",
"NOBB": "NOBB",
"· registrert i appen": "· zarejestrowane w aplikacji",
"Detaljer": "Szczegóły",
"Ingen uttak": "Brak pobrań",
"Bytt bilde": "Zmień zdjęcie",
"Bildet er lagret": "Zdjęcie zapisane",
"Serienummer": "Numer seryjny",
"Står på typeskiltet": "Na tabliczce znamionowej",
"NOBB-nr": "Nr NOBB",
"Merknad": "Uwaga",
"F.eks. lånt ut til Dawid, sendt på service": "Np. pożyczone Dawidowi, wysłane do serwisu",
"Produktinfo og dokumentasjon (NOBB)": "Informacje o produkcie i dokumentacja (NOBB)",
"Slette registreringen?": "Usunąć rejestrację?",
"Hentet fra Visma, ordre": "Pobrane z Visma, zamówienie",
"Kategorien er rettet av leder.": "Kategorię poprawił kierownik.",
"Registrert": "Zarejestrowano",
"Hva er det": "Co to jest",
"F.eks. HiKOKI kombihammer DH36DPA": "Np. HiKOKI młotowiertarka DH36DPA",
"NOBB-nr (valgfritt)": "Nr NOBB (opcjonalnie)",
"Verktøy": "Narzędzia",
"Arbeidstøy": "Odzież robocza",
"Verneutstyr": "Środki ochrony",
"Fått dato": "Data otrzymania",
"Alle ansatte": "Wszyscy pracownicy",
"Ansatt": "Pracownik",
"Forbruk": "Materiały zużywalne",
"Kvote brukt opp": "Limit wykorzystany",
"Bytte ikke avklart": "Wymiana niewyjaśniona",
"· ingen konto": "· brak konta",
"Månedsrapporter": "Raporty miesięczne",
"Ingen rapporter ennå.": "Brak raportów.",
"Utkast": "Wersja robocza",
"Les": "Czytaj",
"Søknaden er sendt": "Wniosek wysłany",
"Sommerferien": "Urlop letni",
"du har søkt om": "wnioskowałeś o",
"dager hovedferie (1. juni–30. september). Søk gjerne snart, så blir sommerplanen klar i god tid.": "dni urlopu głównego (1 czerwca–30 września). Złóż wniosek wcześnie, aby plan letni był gotowy na czas.",
"Saldo": "Saldo",
"feriedager igjen av": "dni urlopu pozostało z",
"Venter": "Oczekuje",
"Hovedferie": "Urlop główny",
"Rett:": "Prawo:",
"Søk ferie": "Złóż wniosek o urlop",
"Fra og med": "Od (włącznie)",
"Til og med": "Do (włącznie)",
"Merknad (valgfritt)": "Uwaga (opcjonalnie)",
"F.eks. hytteferie, kan nås på telefon": "Np. wyjazd, dostępny pod telefonem",
"Velg datoer, så sjekker appen saldo, varsel, hovedferie og bemanning med en gang.": "Wybierz daty, a aplikacja od razu sprawdzi saldo, termin, urlop główny i obsadę.",
"Send søknad": "Wyślij wniosek",
"Mine søknader": "Moje wnioski",
"Legg all ferie": "Dodaj cały urlop",
"i kalenderen": "do kalendarza",
"Søknaden er trukket": "Wniosek wycofany",
"Trekk": "Wycofaj",
"Legg i kalender": "Dodaj do kalendarza",
"Ingen søknader for": "Brak wniosków na",
"avslått": "odrzucony",
"Forrige måned": "Poprzedni miesiąc",
"Neste måned": "Następny miesiąc",
"Sommer": "Lato",
"Borte totalt": "Nieobecni łącznie",
"For mange borte i én avdeling": "Zbyt wielu nieobecnych w jednym dziale",
"Søndag eller helligdag": "Niedziela lub święto",
"Over bemanningsgrensen": "Ponad limit obsady",
"Ukjent": "Nieznany",
"Godkjenn": "Zatwierdź",
"Avslå": "Odrzuć",
"Hvor mye ferie": "Ile urlopu",
"Hvem bestemmer tidspunktet": "Kto ustala termin",
"Hovedferie om sommeren": "Urlop główny latem",
"Den ansatte kan kreve 3 uker sammenhengende ferie i perioden 1. juni til 30. september (18 virkedager etter loven, 15 feriedager mandag–fredag).": "Pracownik może żądać 3 tygodni nieprzerwanego urlopu w okresie od 1 czerwca do 30 września (18 dni roboczych według ustawy, 15 dni urlopu pon.–pt.).",
"Restferien": "Pozostały urlop",
"Restferien kan kreves gitt samlet i løpet av ferieåret.": "Pozostały urlop można żądać w całości w ciągu roku urlopowego.",
"Ferie skal tas": "Urlop trzeba wykorzystać",
"Ferien skal tas i ferieåret, og arbeidsgiver skal sørge for at den blir avviklet.": "Urlop należy wykorzystać w roku urlopowym, a pracodawca musi zadbać o jego wykorzystanie.",
"Overføring": "Przeniesienie",
"Syk i ferien": "Choroba w czasie urlopu",
"Blir den ansatte helt arbeidsufør i ferien og dokumenterer det med legeerklæring, kan hen kreve tilsvarende antall dager utsatt ferie senere i året.": "Jeśli pracownik stanie się całkowicie niezdolny do pracy w czasie urlopu i udokumentuje to zaświadczeniem lekarskim, może żądać odpowiedniej liczby dni urlopu później w roku.",
"Feriepenger": "Ekwiwalent urlopowy (feriepenger)",
"10,2 % av feriepengegrunnlaget fra året før, eller 12 % med femte ferieuke. Ansatte over 60 år får 2,3 prosentpoeng ekstra.": "10,2 % podstawy z poprzedniego roku lub 12 % przy piątym tygodniu urlopu. Pracownicy powyżej 60 lat otrzymują dodatkowo 2,3 punktu procentowego.",
"Ferieloven i korte trekk": "Ustawa o urlopach w skrócie",
"Lovdata": "Lovdata",
"Ferieloven": "Ustawa o urlopach",
"Dette sjekker appen automatisk": "To aplikacja sprawdza automatycznie",
"Meld fravær": "Zgłoś nieobecność",
"Type fravær": "Rodzaj nieobecności",
"Når barnet ditt er sykt og du må være hjemme. Rett på 10 dager i året (15 med mer enn to barn, dobbelt for alenemor/-far).": "Gdy twoje dziecko jest chore i musisz zostać w domu. Prawo do 10 dni w roku (15 przy więcej niż dwojgu dzieciach, podwójnie dla samotnych rodziców).",
"Når legen har sykmeldt deg. Legg inn perioden og graden som står på sykmeldingen.": "Gdy lekarz wystawił ci zwolnienie. Wpisz okres i stopień ze zwolnienia lekarskiego.",
"Grad %": "Stopień %",
"F.eks. tilbake mandag": "Np. wracam w poniedziałek",
"Ikke skriv hva du er syk av – det har ikke arbeidsgiver krav på å vite.": "Nie pisz, na co chorujesz – pracodawca nie ma prawa tego wiedzieć.",
"Egenmelding kan gjelde høyst": "Zwolnienie własne (egenmelding) może obejmować najwyżej",
"dager. Lengre fravær krever sykmelding fra lege.": "dni. Dłuższa nieobecność wymaga zwolnienia lekarskiego.",
"Du har brukt egenmelding": "Wykorzystałeś zwolnienie własne",
"ganger de siste 12 månedene. Snakk med leder – det kan kreves sykmelding.": "razy w ciągu ostatnich 12 miesięcy. Porozmawiaj z kierownikiem – może być wymagane zwolnienie lekarskie.",
"Ditt fravær": "Twoja nieobecność",
"Egenmelding": "Zwolnienie własne (egenmelding)",
"Dager, 12 mnd": "Dni, 12 mies.",
"Sykt barn": "Chore dziecko",
"Arbeidsgiverperioden": "Okres płacony przez pracodawcę",
"(fravær fra": "(nieobecność od",
"av 16 dager brukt.": "z 16 dni wykorzystano.",
"Arbeidsgiver betaler.": "Płaci pracodawca.",
"Ingen fravær registrert.": "Brak zarejestrowanej nieobecności.",
"Fravær – oversikt": "Nieobecność – przegląd",
"Borte i dag:": "Nieobecni dzisiaj:",
"Egenmelding 12 mnd": "Zwolnienie własne 12 mies.",
"Sykmeldt": "Na zwolnieniu lekarskim",
"Avslått": "Odrzucony",
"Leder:": "Kierownik:",
"Ny lenke laget. Den gamle virker ikke lenger.": "Utworzono nowy link. Stary już nie działa.",
"Lenken er kopiert.": "Link skopiowany.",
"Kunne ikke kopiere. Marker lenken og kopier den selv.": "Nie udało się skopiować. Zaznacz link i skopiuj go sam.",
"Ferien i mobilkalenderen": "Urlop w kalendarzu telefonu",
"Abonner én gang, så dukker godkjent ferie opp i kalenderen din av seg selv. Endringer kommer med etter noen timer.": "Zasubskrybuj raz, a zatwierdzony urlop sam pojawi się w twoim kalendarzu. Zmiany pojawiają się po kilku godzinach.",
"Henter …": "Pobieranie …",
"Vis kalenderlenke": "Pokaż link do kalendarza",
"Abonner (iPhone og Mac)": "Subskrybuj (iPhone i Mac)",
"Kopier lenke": "Kopiuj link",
"Kalenderlenke": "Link do kalendarza",
"iPhone:": "iPhone:",
"trykk «Abonner» og deretter «Abonner» igjen i kalenderen.": "naciśnij «Subskrybuj», a potem jeszcze raz «Subskrybuj» w kalendarzu.",
"Android / Google Kalender:": "Android / Kalendarz Google:",
"kopier lenken, åpne calendar.google.com på PC, velg «Andre kalendere» → «+» → «Fra nettadresse» og lim inn. Den dukker så opp på telefonen.": "skopiuj link, otwórz calendar.google.com na komputerze, wybierz «Inne kalendarze» → «+» → «Z adresu URL» i wklej. Potem pojawi się w telefonie.",
"Outlook:": "Outlook:",
"«Legg til kalender» → «Abonner fra nettet» og lim inn lenken.": "«Dodaj kalendarz» → «Subskrybuj z sieci» i wklej link.",
"Lenken er personlig. Del den ikke med andre.": "Link jest osobisty. Nie udostępniaj go innym.",
"Lag ny lenke": "Utwórz nowy link",
"Oversikt": "Przegląd",
"Historikk": "Historia",
"Økonomi": "Finanse",
"Sluttdokumentasjon": "Dokumentacja końcowa",
"‹ Alle prosjekter": "‹ Wszystkie projekty",
"· kundenr": "· nr klienta",
"Materiell brukt": "Zużyty materiał",
"varer fra Visma)": "towarów z Visma)",
"Vare": "Towar",
"Antall": "Ilość",
"Vis færre": "Pokaż mniej",
"søndag": "niedziela",
"lørdag": "sobota",
"Ingenting registrert på prosjektet ennå.": "Na projekcie jeszcze nic nie zarejestrowano.",
"Vis eldre dager (": "Pokaż starsze dni (",
"Timer og plan": "Godziny i plan",
"Brukt": "Wykorzystane",
"Kalkulert": "Skalkulowane",
"+ tillegg": "+ dodatki",
"Planlagt:": "Zaplanowano:",
"Timer per person": "Godziny na osobę",
"Notat til snekkerne": "Notatka dla stolarzy",
"Dagboken er oppdatert": "Dziennik zaktualizowany",
"Skriv i dagboken": "Napisz w dzienniku",
"Vær": "Pogoda",
"Hva ble gjort i dag?": "Co zrobiono dzisiaj?",
"F.eks. Montert 6 vinduer i 2. etasje, beslått utvendig.": "Np. zamontowano 6 okien na 2. piętrze, obróbki na zewnątrz.",
"Hindringer eller ventetid": "Przeszkody lub czekanie",
"F.eks. Venter på levering, kunden ikke hjemme, regn stoppet arbeid": "Np. czekanie na dostawę, klienta nie ma w domu, deszcz wstrzymał pracę",
"Dagbok": "Dziennik",
"Hindring:": "Przeszkoda:",
"Ingen dagbokinnslag ennå.": "Brak wpisów w dzienniku.",
"Tilleggsarbeidet er registrert": "Prace dodatkowe zarejestrowane",
"Nytt tilleggsarbeid": "Nowe prace dodatkowe",
"Arbeid som ikke var med i tilbudet. Registrer det med en gang, og la kunden signere på skjermen, så blir det ikke glemt på fakturaen.": "Prace, których nie było w ofercie. Zarejestruj je od razu i daj klientowi podpisać na ekranie, żeby nie zostały pominięte na fakturze.",
"Hva skal gjøres?": "Co trzeba zrobić?",
"F.eks. Skifte råtten svill under vindu": "Np. wymiana spróchniałego progu pod oknem",
"Timer (anslag)": "Godziny (szacunkowo)",
"Pris eks. mva (valgfritt)": "Cena netto (opcjonalnie)",
"Materiell": "Materiał",
"F.eks. 2 stk 48x148 impregnert, 3 m": "Np. 2 szt. 48x148 impregnowane, 3 m",
"Tilleggsarbeid": "Prace dodatkowe",
"Signert av": "Podpisał(a)",
"Kunden signerer": "Klient podpisuje",
"Fakturert": "Zafakturowane",
"Avvist": "Odrzucone",
"Ingen tilleggsarbeid registrert.": "Brak zarejestrowanych prac dodatkowych.",
"Signert av kunden": "Podpisane przez klienta",
"Kundesignatur": "Podpis klienta",
"Godkjenning av tilleggsarbeid": "Zatwierdzenie prac dodatkowych",
"Faktureres etter medgått tid og materiell.": "Fakturowane według czasu i materiału.",
"Kundens navn": "Imię i nazwisko klienta",
"Signer med fingeren": "Podpisz palcem",
"Tøm": "Wyczyść",
"Søk i prosjekter": "Szukaj projektów",
"Søk på nr, navn, kunde": "Szukaj po nr, nazwie, kliencie",
"Vis avsluttede": "Pokaż zakończone",
"Prosjekter og kunder hentes automatisk fra Visma Business NXT.": "Projekty i klienci są pobierani automatycznie z Visma Business NXT.",
"Prosjekter med aktivitet sist står øverst.": "Projekty z ostatnią aktywnością są na górze.",
"Nr": "Nr",
"Sist aktivitet": "Ostatnia aktywność",
"· du har ført timer her": "· wpisywałeś tu godziny",
"åpne avvik": "otwarte zdarzenia",
"over kalkyle": "ponad kalkulację",
"snart brukt opp": "prawie wykorzystane",
"Ingen prosjekter passer søket.": "Żaden projekt nie pasuje do wyszukiwania.",
"Ingen prosjekter ennå.": "Brak projektów.",
"Sluttdato er før startdato.": "Data końcowa jest przed datą początkową.",
"Del opp ferie over nyttår i to søknader, én for hvert ferieår.": "Podziel urlop na przełomie roku na dwa wnioski, po jednym na każdy rok urlopowy.",
"Perioden har ingen feriedager (bare helg eller helligdager).": "W tym okresie nie ma dni urlopu (tylko weekend lub święta).",
"Du": "Ty",
"Perioden starter tilbake i tid.": "Okres zaczyna się w przeszłości.",
"Mindre enn 2 måneders varsel. Ansatte har rett til å få vite ferietidspunktet senest 2 måneder før, så dette krever enighet med leder (ferieloven § 6).": "Mniej niż 2 miesiące wyprzedzenia. Pracownik ma prawo poznać termin urlopu najpóźniej 2 miesiące wcześniej, więc wymaga to zgody kierownika (ustawa o urlopach § 6).",
"Minst 2 måneders varsel.": "Co najmniej 2 miesiące wyprzedzenia.",
"Sykmelding": "Zwolnienie lekarskie",
"Uønsket hendelse (RUH)": "Niepożądane zdarzenie (RUH)",
"Skade på person": "Uraz osoby",
"Forbedringsforslag": "Propozycja usprawnienia",
"Åpen": "Otwarte",
"Under arbeid": "W trakcie",
"Lukket": "Zamknięte",
"Ikke signert": "Niepodpisane",
"Signert av kunde": "Podpisane przez klienta",
"Sol": "Słońce",
"Skyet": "Pochmurno",
"Regn": "Deszcz",
"Snø": "Śnieg",
"Vind": "Wiatr",
"Kuling": "Wichura",
"Frost": "Mróz",
"I bruk": "W użyciu",
"Til service": "W serwisie",
"Levert inn": "Zwrócone",
"Tapt": "Zgubione",
"Vernesko": "Obuwie ochronne",
"Vinterjakke/-bukse": "Kurtka/spodnie zimowe",
"Regntøy": "Odzież przeciwdeszczowa",
"Arbeidsbukser": "Spodnie robocze",
"Arbeidsjakker": "Kurtki robocze",
"Gensere": "Bluzy",
"Sluttid må være etter starttid, og lunsjen kan ikke være lengre enn arbeidsøkta.": "Godzina zakończenia musi być po rozpoczęciu, a przerwa nie może być dłuższa niż sesja pracy.",
"Du har ikke tilgang til å gjøre dette.": "Nie masz uprawnień, aby to zrobić.",
"Koden er feil eller utløpt. Be om en ny kode.": "Kod jest błędny lub wygasł. Poproś o nowy kod.",
"For mange forsøk. Vent et minutt og prøv igjen.": "Zbyt wiele prób. Odczekaj minutę i spróbuj ponownie.",
"Får ikke kontakt med serveren. Sjekk nettet og prøv igjen.": "Brak połączenia z serwerem. Sprawdź internet i spróbuj ponownie.",
"1. nyttårsdag": "Nowy Rok",
"Skjærtorsdag": "Wielki Czwartek",
"Langfredag": "Wielki Piątek",
"1. påskedag": "Niedziela Wielkanocna",
"2. påskedag": "Poniedziałek Wielkanocny",
"Arbeidernes dag": "Święto Pracy",
"Grunnlovsdag": "Dzień Konstytucji",
"Kristi himmelfartsdag": "Wniebowstąpienie",
"1. pinsedag": "Zesłanie Ducha Świętego",
"2. pinsedag": "Drugi dzień Zielonych Świątek",
"1. juledag": "Boże Narodzenie",
"2. juledag": "Drugi dzień świąt",
"januar": "styczeń",
"februar": "luty",
"mars": "marzec",
"april": "kwiecień",
"juni": "czerwiec",
"juli": "lipiec",
"august": "sierpień",
"september": "wrzesień",
"oktober": "październik",
"november": "listopad",
"desember": "grudzień",
"Januar": "Styczeń",
"Februar": "Luty",
"Mars": "Marzec",
"April": "Kwiecień",
"Mai": "Maj",
"Juni": "Czerwiec",
"Juli": "Lipiec",
"August": "Sierpień",
"September": "Wrzesień",
"Oktober": "Październik",
"November": "Listopad",
"Desember": "Grudzień",
"Tiden overlapper med en annen registrering samme dag.": "Czas nakłada się na inną rejestrację tego samego dnia.",
"Timene er godkjent og kan bare endres av leder.": "Godziny są zatwierdzone i może je zmienić tylko kierownik.",
"Ja": "Tak",
"Nei": "Nie",
"Ikke logget inn": "Niezalogowany",
"Hele dagen": "Cały dzień",
"Lunsj": "Przerwa obiadowa",
"Uten prosjekt": "Bez projektu",
"feriedager": "dni urlopu",
". Feriedager telles mandag–fredag, så en uke ferie er 5 dager.": ". Dni urlopu liczone są od poniedziałku do piątku, więc tydzień urlopu to 5 dni.",
"maks": "maks.",
"borte": "nieobecnych",
"Loven gir 25 virkedager (lørdag teller), altså 4 uker og 1 dag. Hos N L Austnes teller vi feriedager mandag–fredag, og de ansatte har 25 feriedager, altså 5 uker. Ansatte som fyller 60 år i løpet av ferieåret får én uke ekstra.": "Ustawa daje 25 dni roboczych (sobota się liczy), czyli 4 tygodnie i 1 dzień. W N L Austnes liczymy dni urlopu od poniedziałku do piątku, a pracownicy mają 25 dni urlopu, czyli 5 tygodni. Pracownicy, którzy w roku urlopowym kończą 60 lat, dostają jeden tydzień więcej.",
"Arbeidsgiver fastsetter ferien etter å ha drøftet den med den ansatte eller tillitsvalgt. Den ansatte har rett til å få vite tidspunktet senest 2 måneder før ferien starter, med mindre noe annet er avtalt.": "Pracodawca ustala termin urlopu po omówieniu go z pracownikiem lub przedstawicielem pracowników. Pracownik ma prawo poznać termin najpóźniej 2 miesiące przed rozpoczęciem urlopu, chyba że uzgodniono inaczej.",
"Inntil 2 uker (12 virkedager etter loven) kan overføres til neste ferieår etter skriftlig avtale. Ferie som ikke er tatt på grunn av sykdom eller foreldrepermisjon kan kreves overført.": "Do 2 tygodni (12 dni roboczych według ustawy) można przenieść na następny rok urlopowy na podstawie pisemnej umowy. Urlop niewykorzystany z powodu choroby lub urlopu rodzicielskiego można żądać przenieść.",
"Sammendrag for bruk i appen. Det er selve loven og eventuell tariffavtale som gjelder. Les hele ferieloven på": "Streszczenie na potrzeby aplikacji. Obowiązuje sama ustawa i ewentualny układ zbiorowy. Całą ustawę o urlopach przeczytasz na",
"Antall feriedager mandag–fredag med norske helligdager trukket fra, saldo, 2 måneders varsel, hovedferie i sommerperioden, overlapp med egne søknader og at ikke for mange i samme avdeling er borte samtidig.": "Liczba dni urlopu pon.–pt. bez norweskich świąt, saldo, 2 miesiące wyprzedzenia, urlop główny latem, nakładanie się z własnymi wnioskami oraz to, czy zbyt wielu z tego samego działu nie jest nieobecnych jednocześnie."
};
export const PL_MALER: [string, string][] = [
[
"^(.+?)\\ timer\\ registrert$",
"Zarejestrowano $1 godz."
],
[
"^(.+?)\\ \\(meg\\)$",
"$1 (ja)"
],
[
"^for\\ (.+?)$",
"dla $1"
],
[
"^Før\\ timer\\ for\\ (.+?)$",
"Wpisz godziny dla $1"
],
[
"^·\\ lunsj\\ (.+?)\\ min$",
"· przerwa $1 min"
],
[
"^·\\ reise\\ (.+?)\\ t$",
"· podróż $1 godz."
],
[
"^Uke\\ (.+?)\\ godkjent\\ for\\ (.+?)$",
"Tydzień $1 zatwierdzony dla $2"
],
[
"^Dagen:\\ (.+?)$",
"Dzień: $1"
],
[
"^Logget\\ inn\\ på\\ (.+?)$",
"Zalogowano na $1"
],
[
"^Byttet\\ til\\ (.+?)$",
"Przełączono na $1"
],
[
"^Dagbok(.+?)$",
"Dziennik$1"
],
[
"^(.+?)\\ bilde(.+?)$",
"$1 zdjęć$2"
],
[
"^Tilleggsarbeid:\\ (.+?)\\ ·\\ (.+?)$",
"Prace dodatkowe: $1 · $2"
],
[
"^Hindringer:\\ (.+?)$",
"Przeszkody: $1"
],
[
"^(.+?):\\ (.+?)\\ t,\\ interntid\\ (.+?)\\ t$",
"$1: $2 godz., wewnętrzne $3 godz."
],
[
"^(.+?)\\ lagret$",
"Zapisano $1"
],
[
"^(.+?)\\ bilder\\ er$",
"$1 zdjęć zostało"
],
[
"^Vis\\ bilde\\ (.+?)$",
"Pokaż zdjęcie $1"
],
[
"^(.+?)\\ bilde(.+?)\\ valgt$",
"Wybrano $1 zdjęć$2"
],
[
"^Ansvarlig:\\ (.+?)$",
"Odpowiedzialny: $1"
],
[
"^·\\ frist\\ (.+?)(.+?)$",
"· termin $1$2"
],
[
"^Utstyr\\ –\\ (.+?)$",
"Sprzęt – $1"
],
[
"^siste\\ (.+?)\\ mnd$",
"ostatnie $1 mies."
],
[
"^·\\ ny\\ fra\\ (.+?)$",
"· nowy od $1"
],
[
"^Arbeidstøy\\ (.+?)$",
"Odzież robocza $1"
],
[
"^(.+?)\\ uttak\\ ·\\ sist\\ (.+?)$",
"$1 pobrań · ostatnio $2"
],
[
"^Bilde:\\ (.+?)$",
"Zdjęcie: $1"
],
[
"^Månedsrapport\\ (.+?)$",
"Raport miesięczny $1"
],
[
"^Publisert\\ (.+?)$",
"Opublikowano $1"
],
[
"^Ferie\\ registrert\\ for\\ (.+?)$",
"Urlop zarejestrowany dla $1"
],
[
"^\\+\\ (.+?)\\ \\(over\\ 60\\)$",
"+ $1 (ponad 60 lat)"
],
[
"^\\+\\ (.+?)\\ overført\\ fra\\ (.+?)$",
"+ $1 przeniesione z $2"
],
[
"^Registrer\\ ferie\\ for\\ (.+?)$",
"Zarejestruj urlop dla $1"
],
[
"^Søknader\\ for\\ (.+?)$",
"Wnioski dla $1"
],
[
"^(.+?)\\ registrert(.+?)$",
"Zarejestrowano $1$2"
],
[
"^Meld\\ fravær\\ for\\ (.+?)$",
"Zgłoś nieobecność dla $1"
],
[
"^Når\\ du\\ selv\\ er\\ syk\\.\\ Høyst\\ (.+?)\\ kalenderdager\\ om\\ gangen\\ og\\ (.+?)\\ ganger\\ på\\ 12\\ måneder\\.\\ Lengre\\ fravær\\ krever\\ sykmelding\\ fra\\ lege\\.$",
"Gdy jesteś chory. Najwyżej $1 dni kalendarzowych za jednym razem i $2 razy w ciągu 12 miesięcy. Dłuższa nieobecność wymaga zwolnienia lekarskiego."
],
[
"^NAV\\ betaler\\ sykepenger\\ fra\\ (.+?)\\.\\ Husk\\ inntektsmelding\\ til\\ NAV\\.$",
"NAV wypłaca zasiłek chorobowy od $1. Pamiętaj o zgłoszeniu dochodu do NAV."
],
[
"^(.+?)\\ \\((.+?)\\ til\\ (.+?)\\)$",
"$1 ($2 do $3)"
],
[
"^(.+?)\\ ganger\\ ·\\ (.+?)\\ d$",
"$1 razy · $2 d"
],
[
"^Tillegg(.+?)$",
"Prace dodatkowe$1"
],
[
"^Bilder(.+?)$",
"Zdjęcia$1"
],
[
"^Avvik(.+?)$",
"Zdarzenia$1"
],
[
"^Vis\\ alle\\ (.+?)$",
"Pokaż wszystkie $1"
],
[
"^(.+?)\\ %\\ av\\ kalkulerte\\ timer\\ brukt$",
"Wykorzystano $1 % skalkulowanych godzin"
],
[
"^kr\\ (.+?)\\ eks\\.\\ mva$",
"$1 kr netto"
],
[
"^Signatur\\ (.+?)$",
"Podpis $1"
],
[
"^Anslått\\ (.+?)\\ timer$",
"Szacunkowo $1 godzin"
],
[
"^pris\\ kr\\ (.+?)\\ eks\\.\\ mva$",
"cena $1 kr netto"
],
[
"^materiell:\\ (.+?)$",
"materiał: $1"
],
[
"^(.+?)\\ bilder$",
"$1 zdjęć"
],
[
"^(.+?)\\ %\\ av\\ kalkulerte\\ timer$",
"$1 % skalkulowanych godzin"
],
[
"^(.+?)\\ trekkes\\.\\ Lørdager,\\ søndager\\ og\\ helligdager\\ teller\\ ikke\\.$",
"Odliczono $1. Soboty, niedziele i święta nie są liczone."
],
[
"^Helligdager\\ som\\ ikke\\ trekkes:\\ (.+?)\\.$",
"Święta, które nie są odliczane: $1."
],
[
"^Overlapper\\ med\\ en\\ annen\\ søknad\\ \\((.+?)\\)\\.$",
"Nakłada się na inny wniosek ($1)."
],
[
"^(.+?)\\ har\\ (.+?)\\ igjen\\ i\\ (.+?),\\ søknaden\\ er\\ på\\ (.+?)\\.\\ Ferie\\ utover\\ retten\\ må\\ avtales\\ som\\ ulønnet\\ permisjon\\ eller\\ forskudd\\.$",
"$1 ma jeszcze $2 w $3, wniosek dotyczy $4. Urlop ponad przysługujący wymiar trzeba uzgodnić jako bezpłatny lub zaliczkę."
],
[
"^Innenfor\\ saldo\\.\\ (.+?)\\ igjen\\ etter\\ denne\\.$",
"W ramach salda. Po tym zostanie $1."
],
[
"^Hovedferie\\ 1\\.\\ juni–30\\.\\ september:\\ (.+?)\\ av\\ (.+?)\\ feriedager\\ \\(3\\ uker\\)\\ (.+?)\\ kan\\ kreve\\.$",
"Urlop główny 1 czerwca–30 września: $1 z $2 dni urlopu (3 tygodnie), które $3 może żądać."
],
[
"^(.+?):\\ maks\\ (.+?)\\ borte\\ samtidig\\.\\ Overlapper\\ med\\ (.+?)\\.$",
"$1: maks. $2 nieobecnych jednocześnie. Nakłada się z $3."
],
[
"^(.+?)\\ er\\ alene\\ i\\ (.+?)\\.\\ Avtal\\ hvem\\ som\\ tar\\ henvendelser\\ i\\ perioden\\.$",
"$1 jest sam(a) w $2. Ustalcie, kto przejmuje sprawy w tym okresie."
],
[
"^Bemanningen\\ i\\ (.+?)\\ holder\\.$",
"Obsada w $1 wystarcza."
]
];
