-- Kunden som faktisk faktureres på prosjektet. I Visma står mange prosjekter med firmaet selv som kunde,
-- så for å sammenligne timer med fakturaer brukes kunden på prosjektets ordrer (settes av Visma-hentingen),
-- eller kunden prosjektet hadde i Svenn.
alter table public.prosjekter add column if not exists faktura_kunde_id uuid references public.kunder(id) on delete set null;

-- N L Austnes: kunden fra Svenn for prosjektene som er koblet ved importen
update public.prosjekter p set faktura_kunde_id = k.id
from (values ('Siri Kjerstad Renovering#6','Siri Henriette Kjerstad'),('Terje Aaseli#7','Terje Aaseli'),('Siri Kjerstad Renovering - siri extra#1','Siri Henriette Kjerstad'),('#kunde:Anne Kristina Haram','Anne Kristina Haram'),('#kunde:Ulla. Kenneth','Ulla. Kenneth'),('Daniel Nedreli#9','Nedrelid. Daniel'),('Skulefjellet#5','Øyrådet For Flemsøy/Skuløy'),('Peter Olav Klokk#13','Peter Olav Klokk'),('Kyrre Rogne#14','Rogne. Kyrre'),('Banuch roof#17','Banuch. Jacek'),('Lene Ingelsrud#10837','Ingelsrud. Lene'),('Kjell Arne Olsen#10839','Olsen. Kjell Arne'),('Arild#10844','Anne Kristina Haram'),('ullavegen22 wall#10838','Pettersen. Jan H'),('Enerhaug#10848','Asbjørn Enerhaug'),('Lene Ingelsrud Terrass 2#10851','Ingelsrud. Lene'),('bathroom X#10852','Anne Kristina Haram'),('BAD SIRI#10853','Siri Henriette Kjerstad'),('Innv foring/listing Salongen#10854','Skavland. Karianne'),('Perny Farstad VELUX#10858','Perny Herborg Farstad'),('Skifte bordkledning#10857','Harald Vågene'),('Kjøkken Kjell Arne Olsen#10859','Olsen. Kjell Arne'),('Siri Kjerstad Renovering - Inngangsparti#2','Siri Henriette Kjerstad'),('Skifte bordkledning#10855','Anne Kristine Høgset'),('Ekstra#10865','Harald Vågene'),('Skifte vindu#10856','Ulla. Åsmund'),('Skifte bordkledning - ekstra#1','Anne Kristine Høgset'),('Salongen - Outside Door#10867','Skavland. Karianne'),('Skifte vindu på loftet#10861','Anne Kristine Høgset'),('Siri Kjerstad Renovering - Støyping i kjeller#3','Siri Henriette Kjerstad'),('Skifte vindu ++#10862','Rønstad. Marianne'),('Interntid NL 2026 - Lastebil#2','Byggfag Søvik AS'),('Lastebil#10870','Byggfag Søvik AS'),('ekstra Kjell Arne#10880','Olsen. Kjell Arne')) v(nokkel, kunde)
join public.svenn_kobling sk on sk.nokkel = v.nokkel and sk.prosjekt_id is not null
join public.kunder k on k.navn = v.kunde and k.bedrift_id = sk.bedrift_id
where p.id = sk.prosjekt_id and p.faktura_kunde_id is null;
